@Library(value="ci@master", changelog=false) _

helm_generic([
    directoryPath: "charts/cmp-mgmt",
    imageName: "mynx-use1-pp-cmp-mgmt-ecr",
    app: "cmp-mgmt",
    prefix: "mynx-use1",
    image_tag_helm_path: ".Deployment.containers.cmp-mgmt.image.tag"
])
